### ISSUE TITLE
Arrancar este proyecto! 🚀

### ISSUE THREAD

**Issue by chernando** [OSWeekends/Aprendiendo-RUST#1]
## Documentación

- [x] Revisar el fichero LICENSE
- [x] Revisar el fichero README
- [x] Añadir el fichero CONTRIBUTING
- [x] Añadir el fichero CODE_OF_CONDUCT
- [x] Añadir plantillas para Issues y Pull Requests.

## Código

- [x] Definir convenciones del código.
- [x] El código está claramente documentado.
- [x] No hay material sensible en el proyecto.

## Personas

- [x] Hemos hablado con el departamento legal.
- [x] Hemos anunciado y promocionado el proyecto.
- [x] Hay una persona comprometida en gestionar a la comunidad.
- [x] Al menos dos personas tienen acceso administrativo.

_Lista de tareas basada en https://opensource.guide/starting-a-project/#your-pre-launch-checklist_

**Comment by Josheriff** [comment]
Estoy muy interesado en aprender rust, pero como ya sabéis estoy en demasiados proyectos.

Osea que tenemos que hablar, igual puedo servir de usuario objetivo, hacer ejercicios, lo que sea, pero me interesa 😝

**Comment by chernando** [comment]
@Josheriff 

![](https://i.imgur.com/90yZESB.gif)

**Comment by chernando** [comment]
Por el momento no veo claro una plantilla tipo para los *Issues*.

**Comment by chernando** [comment]
Ok, la base filosófica está 👍
